# Site settings
title: xxOSX
email: evangelos@posteo.eu
description: 
baseurl: "/blog"
url: "http://www.xxosx.com" # the base hostname & protocol for your site
twitter_username: 3vangelos
github_username:  3vangelos

# Build settings
markdown: kramdown
